### ISSUE TITLE
More info about the edition? 

### ISSUE THREAD

**Issue by mrgreekgeek** [byztxt/greektext-stephens#2]
Could a little more information be added to the description for this text? Stephens [was known by several different names](https://en.wikipedia.org/wiki/Robert_Estienne) and he printed several texts in different years. Presumably this is the 1550 edition?

**Comment by normansimonr** [comment]
@mrgreekgeek It is indeed the 1550 edition (you can find collations with the Robinson-Pierpont text [here](https://byzantinetext.com/study/editions/robinson-pierpont/)).

**Comment by normansimonr** [comment]
I just updated the README in commit 4314af2042d9e77b2ce5c1c86d0c49325dd81684

Thanks for bringing this up to our attention!
